server:
  port: 8001

spring:
  application:
    name: innerjoinus-studygroup

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/communityfordeveloper
    username: swcamp
    password: swcamp

  jpa:
    hibernate:
      ddl-auto:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka