server:
  port: 0

spring:
  application:
    name:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/communityfordeveloper
    username: swcamp
    password: swcamp

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

